import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt">
			<head>
				<meta charSet="utf-8" />
				<title>ZebraTravel</title>
				{/* <!-- Stylesheets --> */}
				<link href="/css/bootstrap.css" rel="stylesheet" />
				<link href="/css/style.css" rel="stylesheet" />
				<link
					rel="shortcut icon"
					href="images/favicon.png"
					type="image/x-icon"
				/>
				<link rel="icon" href="images/favicon.png" type="image/x-icon" />
				{/* <!-- Responsive --> */}
				<meta httpEquiv="X-UA-Compatible" content="IE=edge" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
				/>
				<link href="/css/responsive.css" rel="stylesheet" />
				{/* <!--[if lt IE 9]> */}
				<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
				{/* <![endif]-->  */}
			</head>

			<body>
				<div className="page-wrapper">
					{/* <!-- Preloader --> */}
					<div className="preloader"></div>

					<div className="search-backdrop"></div>
					<Navbar />
					{children}
					<Footer />
				</div>
				{/* <!--End pagewrapper-->  */}

				{/* <!--Scroll to top--> */}
				<div className="scroll-to-top scroll-to-target" data-target="html">
					<span className="icon">
						<img src="/images/icons/arrow-up.svg" alt="" title="Go To Top" />
					</span>
				</div>

				<script src="/js/jquery.js"></script>
				<script src="/js/popper.min.js"></script>
				<script src="/js/bootstrap.min.js"></script>
				<script src="/js/jquery-ui.js"></script>
				<script src="/js/jquery.fancybox.js"></script>
				<script src="/js/isotope.js"></script>
				<script src="/js/touchspin.js"></script>
				<script src="/js/owl.js"></script>
				<script src="/js/wow.js"></script>
				<script src="/js/custom-script.js"></script>
			</body>
		</html>
	);
}
